from __future__ import annotations

VERSION = "3.9"
REPORT_VERSION = "v3.9"
PACKAGE_VERSION = "0.3.9"
APP_EDITION = "CHANNEL + GENRE / FAST FULLNESS ENGINE"
APP_TITLE = f"HARU / SUNO 15-SET MASTERING v{VERSION}"
DISPLAY_VERSION = f"HARU Mastering v{VERSION}"
FULLNESS_NAME = f"HARU Mastering v{VERSION} - {APP_EDITION}"
