from __future__ import annotations

VERSION = "3.8.1"
REPORT_VERSION = "v3.8.1"
PACKAGE_VERSION = "0.3.8.1"
APP_EDITION = "FULLNESS ENGINE"
APP_TITLE = f"HARU / SUNO 15-SET MASTERING v{VERSION}"
DISPLAY_VERSION = f"HARU Mastering v{VERSION}"
FULLNESS_NAME = f"HARU Mastering v{VERSION} - {APP_EDITION}"
