from __future__ import annotations

VERSION = "3.8"
REPORT_VERSION = "v3.8"
PACKAGE_VERSION = "0.3.8"
APP_EDITION = "FULLNESS ENGINE"
APP_TITLE = f"HARU / SUNO 15-SET MASTERING v{VERSION} - {APP_EDITION}"
DISPLAY_VERSION = f"HARU Mastering v{VERSION}"
FULLNESS_NAME = "HARU Mastering v3.8 - FULLNESS ENGINE"
